### ISSUE TITLE
Appears in the NgModule.imports of CoreModule, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by MaliahRajan** [PascalHonegger/ng-datatable#1]
ERROR in node_modules/@pascalhonegger/ng-datatable/lib/src/DataTableModule.d.ts:1:22 - error TS-996002: Appears in the NgModule.imports of CoreModule, but could not be resolved to an NgModule class

{
  "name": "angular-sample",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/pwa": "^0.803.26",
    "@angular/router": "^8.2.14",
    "@angular/service-worker": "^8.2.14",
    "@ngx-formly/core": "^5.0.0",
    **"@pascalhonegger/ng-datatable": "8.0.0",**
    "@types/c3": "^0.7.4",
    "@types/lodash": "^4.14.155",
    "feather-icons": "^4.28.0",
    "file-saver": "^2.0.2",
    "lodash": "^4.17.15",
    "ngx-csv": "^0.3.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.11.1",
    "xlsx": "^0.15.6",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.26",
    "@angular/cli": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

Temporary fix : 

aot - false &  buildoptimizer - false

Any permanant fix ?

**Comment by PascalHonegger** [comment]
It appears you're using Angular 8 with ivy?
I've had issues with that configuration and reorganized the whole project in Version 9.0. That version is Angular 9 and ivy compatible. It might work given Angular 8 in your project, but I haven't tested it.

**Comment by MaliahRajan** [comment]
Thank your quick reply. I tried upgrading @pascalhonegger/ng-datatable": "9.0.1" and getting -
" ERROR in No suitable injection token for parameter 'differs' of class 'DataTable'.
no type or decorator " 

Faced before ?

**Comment by PascalHonegger** [comment]
I haven't seen that one, are you also using Angular 9? If not, I guess you only have two options: Either update to Angular 9 or disable the ivy compiler in Angular 8. If the problem persists in Angular 9 I'll try to do further investigations, but I haven't had any problems so far.

**Comment by MaliahRajan** [comment]
Sure, will proceed with the IVY workaround in Angular 8. It would be great if you can figure out this error in Angular 8 
" ERROR in No suitable injection token for parameter 'differs' of class 'DataTable'.
no type or decorator "

**Comment by PascalHonegger** [comment]
The DaataTable class is simply trying to resolve the Angular internal tpye "IterableDiffers". I assume this is just an Angular Ivy internal issue and has since been resolved in Angular 9. I've upgraded multiple projects from Angular 8 to 9 without major issues and recommend you to do the same in case you want to truly fix this issue (and reduce your bundle size).
