### ISSUE TITLE
angular style guide

### ISSUE THREAD

**Issue by sysmat** [PascalHonegger/ng-datatable#10]
- this lib doesn't follow angular style guide
- "eslint": "^8.25.0", and off -> error produce a lot of errors(22)

**Comment by PascalHonegger** [comment]
I don't understand what you're trying to say. This project uses `eslint` and `ng lint` passes without any errors. I've upgraded all dependencies within this project to the latest and also updated the linting configuration to include the demo project. I welcome you to submit a PR with a fix if this doesn't suite you.

**Comment by sysmat** [comment]
1. upgrade `"eslint": "^8.23.1"` to "eslint": "^8.25.0",
2. upgrade ng 14.0.0  →   ^14.2.6
3. in ng-datatable/.eslintrc.json change rules from **off** to **error**

```json
"rules": {
        "@angular-eslint/directive-selector": "error",
        "@angular-eslint/directive-class-suffix": "error",
        "@angular-eslint/component-selector": "error",
        "@angular-eslint/component-class-suffix": "error",
        "@angular-eslint/no-conflicting-lifecycle": "error",
        "@angular-eslint/no-input-rename": "error",
        "@angular-eslint/no-output-rename": "error"
      }
```
4. run `npm run lint` and you will get es-lint errors: ✖ 17 problems (17 errors, 0 warnings)

**Comment by sysmat** [comment]
# Errors are of this types:

- Component class names should end with one of these suffixes: "Component" (https://angular.io/styleguide#style-02-03) 
- Directive class names should end with one of these suffixes: "Directive" (https://angular.io/styleguide#style-02-03) 
- Implementing DoCheck and OnChanges in a class is not recommended  
-  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)
- Output bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)  
-  Declaring ngDoCheck and ngOnChanges method in a class is not recommended

**Comment by sysmat** [comment]
```
GitHub\ng-datatable\projects\ng-datatable\src\lib\DataTable.ts

   31:14  error  Directive class names should end with one of these suffixes: "Directive" (https://angular.io/styleguide#style-02-03)  @angular-eslint/directive-class-suffix
   31:35  error  Implementing DoCheck and OnChanges in a class is not recommended                                                      @angular-eslint/no-conflicting-lifecycle
   31:46  error  Implementing DoCheck and OnChanges in a class is not recommended                                                      @angular-eslint/no-conflicting-lifecycle
   34:12  error  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                                @angular-eslint/no-input-rename
   36:12  error  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                                @angular-eslint/no-input-rename
   37:12  error  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                                @angular-eslint/no-input-rename
   38:13  error  Output bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                               @angular-eslint/no-output-rename
   39:13  error  Output bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                               @angular-eslint/no-output-rename
   41:12  error  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                                @angular-eslint/no-input-rename
   42:12  error  Input bindings should not be aliased (https://angular.io/guide/styleguide#style-05-13)                                @angular-eslint/no-input-rename
  105:5   error  Declaring ngDoCheck and ngOnChanges method in a class is not recommended                                              @angular-eslint/no-conflicting-lifecycle
  129:5   error  Declaring ngDoCheck and ngOnChanges method in a class is not recommended                                              @angular-eslint/no-conflicting-lifecycle


```

**Comment by PascalHonegger** [comment]
All of these issues are explicitly ignored in the [.eslintrc](https://github.com/PascalHonegger/ng-datatable/blob/master/projects/ng-datatable/.eslintrc.json#L19-L25) because I can't fix them easily without introducing breaking changes to either the API or implementation

**Comment by sysmat** [comment]
Yes, I understand, sorry for noise
