### ISSUE TITLE
Descending sort with null values are pushed on top instead of bottom

### ISSUE THREAD

**Issue by fzs1994** [PascalHonegger/ng-datatable#2]
In table when sorting any column, if that value has null, then those are pushed on top instead of bottom. How to fix that?
![image](https://user-images.githubusercontent.com/10684213/91399067-f1398200-e85a-11ea-8e98-5866755d5125.png)

**Comment by PascalHonegger** [comment]
This component uses the [lodash orderBy function](https://lodash.com/docs/4.17.15#orderBy). When sorting descending, null values appear on top and empty strings at the bottom. On the contrary when sorting ascendingly, empty string are at the top and null values at the bottom. I don't know your use case exactly, but maybe using an empty string intead of null could solve the issue.

**Comment by fzs1994** [comment]
Thanks a lot! This is working fine with blank string!
