### ISSUE TITLE
not showing the triangules in header column when sorting

### ISSUE THREAD

**Issue by cijt** [PascalHonegger/ng-datatable#3]
Hello.
 i've implemented the plugin an it's working. Is paginating and when clicking in header's titles the table sorts .

The problem is that in the headers is not showing the little triangle indicating the column that is sorting  and if the sorting is asc or dec.

is there any solution for this?. Thank you very mucho

**Comment by PascalHonegger** [comment]
The little triangle indicators are from Glyphicons and should be loaded if you have bootstrap included. Are you using Bootstrap 4 by any chance?

**Comment by cijt** [comment]
i have installed bootstrap 4. this is my angular hson lines:

            "styles": [
              "src/assets/css/font-awesome.min.css",
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/assets/less/styles.less",
              "src/assets/less/responsive.less"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "src/assets/js/libs/popper1_16_0/popper.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.min.js"
            ]

my package.json

{
  "name": "mega2-app-incidencias",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@ng-bootstrap/ng-bootstrap": "^8.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@pascalhonegger/ng-datatable": "^11.0.1",
    "bootstrap": "^4.5.3",
    "jquery": "^3.5.1",
    "ngx-slide-toggle": "^0.1.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.1",
    "@angular/cli": "~11.0.1",
    "@angular/compiler-cli": "~11.0.0",
    "@angular/localize": "^11.0.5",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

i also installed ng bootstrap.

thank you for your response

**Comment by PascalHonegger** [comment]
Yeah the code corrently depends on Glyphicons, which were included in Bootstrap 3. I'm not sure if I should switch to Bootstrap 4 given how dated Bootstrap 3 has become, but maybe some applications still rely on it :/
As a workaround you can try to include Glyphicons explicitly

**Comment by cijt** [comment]
I've installed glyphicons separately into my projet and the problem is solved.

Thank you very much.
