### ISSUE TITLE
CommonJS/AMD lodash dependency

### ISSUE THREAD

**Issue by PavolSvidran** [PascalHonegger/ng-datatable#4]
Hi, i am using this package for my project, and after update to Angular 10 i got this ugly warning:

`WARNING in \@pascalhonegger\ng-datatable\fesm2015\pascalhonegger-ng-datatable.js depends on 'lodash'. CommonJS or AMD dependencies can cause optimization bailouts.`

This issue should be simple resolved by replacing lodash for lodash-es. Could you change that in future update? Thanks.

**Comment by PascalHonegger** [comment]
I've released version 11.1.0 which removes the lodash dependency in it's entirety. If you have further problems or suggestions I'll also happily accept pull requests 😉
