### ISSUE TITLE
"bootstrap": "4.6.0"

### ISSUE THREAD

**Issue by sysmat** [PascalHonegger/ng-datatable#5]
It would be great if using higher version of bootstrap

**Comment by PascalHonegger** [comment]
I agree that Bootstrap 4 (and Bootstrap 5 once released) would be a nice addition to this project. I don't know how to go about supporting new Bootstrap version, I see the following issues:

- Backwards compatibility to existing users which cannot migrate their Bootstrap Version (e.g. configureable via angular injection token)
- Ascending / Descending icons as newer bootstrap version do not include a glyph library (probably configurable via angular inejction)

For the mean time it should look decent given Bootstrap 4 and Glyphicons, but I haven't tested it personally.

**Comment by PascalHonegger** [comment]
@sysmat I decided to just upgrade to the latest Bootstrap 5 release together with an Angular 13 upgrade, released in version `13.0.0`.

If you want you can give it a try and provide feedback if you encounter any issues. Given that Bootstrap 3 is end of life and Bootstrap 4 only has LTS and will go EOL in one year I think this move is appropriate.

**Comment by PascalHonegger** [comment]
@sysmat I believe this is fixed with the inclusion of Bootstrap 5, if you still have any issues you can re-open this issue
