### ISSUE TITLE
Does It have Functionality of Server Pagination?

### ISSUE THREAD

**Issue by sanaa5127** [PascalHonegger/ng-datatable#9]
I was using angular2-datatable-serverpagination in my project with Angular version 7, Now I have updated my Project to angular version 14 and I have found this package which is compatible with with angular 14 with almost no changes in code. Now my only concern is that does it allow server pagination? If not then suggest some similar package with no code changes and server pagination. 

I would be so thankful!

**Comment by PascalHonegger** [comment]
Sorry for the very late response, I just totally forgot about it 😨 
I'm not the original author of this package but I don't think server pagination is a feature at the moment. I've only done little changes to the code itself, you could probably quite easily adapt the existing serverpagination package to extend my fork and also work with newer Angular / TS versions.
